-- | Bindings for @river-layer-shell-v1.xml@.
--
-- Generated by @codegen/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.LayerShell
  (
    RiverLayerShellV1Event(..)
  , riverLayerShellV1Interface
  , riverLayerShellV1Version
  , riverLayerShellV1Listen
  , riverLayerShellV1Destroy
  , riverLayerShellV1GetOutput
  , riverLayerShellV1GetSeat
  , riverLayerShellV1ErrorObjectAlreadyCreated
  , RiverLayerShellOutputV1Event(..)
  , riverLayerShellOutputV1Interface
  , riverLayerShellOutputV1Version
  , riverLayerShellOutputV1Listen
  , riverLayerShellOutputV1Destroy
  , riverLayerShellOutputV1SetDefault
  , RiverLayerShellSeatV1Event(..)
  , riverLayerShellSeatV1Interface
  , riverLayerShellSeatV1Version
  , riverLayerShellSeatV1Listen
  , riverLayerShellSeatV1Destroy
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_layer_shell_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLayerShellV1Interface :: ByteString
riverLayerShellV1Interface = "river_layer_shell_v1"

-- | The highest version these bindings were generated against.
riverLayerShellV1Version :: Word32
riverLayerShellV1Version = 1

-- | @river_layer_shell_v1.error.object_already_created@
riverLayerShellV1ErrorObjectAlreadyCreated :: Word32
riverLayerShellV1ErrorObjectAlreadyCreated = 0

-- | @river_layer_shell_v1.destroy@
riverLayerShellV1Destroy :: Connection -> ObjectId -> IO ()
riverLayerShellV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_layer_shell_v1.get_output@
riverLayerShellV1GetOutput :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverLayerShellV1GetOutput conn self output =
  do
    id_ <- newObject conn
    request conn self 1 (argObject id_ <> argObject output)
    pure id_

-- | @river_layer_shell_v1.get_seat@
riverLayerShellV1GetSeat :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverLayerShellV1GetSeat conn self seat =
  do
    id_ <- newObject conn
    request conn self 2 (argObject id_ <> argObject seat)
    pure id_

-- | Events delivered to a @river_layer_shell_v1@.
data RiverLayerShellV1Event
  = RiverLayerShellV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_layer_shell_v1@ object.
riverLayerShellV1Listen :: Connection -> ObjectId -> (RiverLayerShellV1Event -> IO ()) -> IO ()
riverLayerShellV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverLayerShellV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_layer_shell_output_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLayerShellOutputV1Interface :: ByteString
riverLayerShellOutputV1Interface = "river_layer_shell_output_v1"

-- | The highest version these bindings were generated against.
riverLayerShellOutputV1Version :: Word32
riverLayerShellOutputV1Version = 1

-- | @river_layer_shell_output_v1.destroy@
riverLayerShellOutputV1Destroy :: Connection -> ObjectId -> IO ()
riverLayerShellOutputV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_layer_shell_output_v1.set_default@
riverLayerShellOutputV1SetDefault :: Connection -> ObjectId -> IO ()
riverLayerShellOutputV1SetDefault conn self =
  request conn self 1 (mempty)

-- | Events delivered to a @river_layer_shell_output_v1@.
data RiverLayerShellOutputV1Event
  = RiverLayerShellOutputV1NonExclusiveArea !Int32 !Int32 !Int32 !Int32
  | RiverLayerShellOutputV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_layer_shell_output_v1@ object.
riverLayerShellOutputV1Listen :: Connection -> ObjectId -> (RiverLayerShellOutputV1Event -> IO ()) -> IO ()
riverLayerShellOutputV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 ->
      handler =<< decode (RiverLayerShellOutputV1NonExclusiveArea <$> getInt <*> getInt <*> getInt <*> getInt) body
    _ -> handler (RiverLayerShellOutputV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_layer_shell_seat_v1 (version 1)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverLayerShellSeatV1Interface :: ByteString
riverLayerShellSeatV1Interface = "river_layer_shell_seat_v1"

-- | The highest version these bindings were generated against.
riverLayerShellSeatV1Version :: Word32
riverLayerShellSeatV1Version = 1

-- | @river_layer_shell_seat_v1.destroy@
riverLayerShellSeatV1Destroy :: Connection -> ObjectId -> IO ()
riverLayerShellSeatV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | Events delivered to a @river_layer_shell_seat_v1@.
data RiverLayerShellSeatV1Event
  = RiverLayerShellSeatV1FocusExclusive
  | RiverLayerShellSeatV1FocusNonExclusive
  | RiverLayerShellSeatV1FocusNone
  | RiverLayerShellSeatV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_layer_shell_seat_v1@ object.
riverLayerShellSeatV1Listen :: Connection -> ObjectId -> (RiverLayerShellSeatV1Event -> IO ()) -> IO ()
riverLayerShellSeatV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverLayerShellSeatV1FocusExclusive
    1 -> handler RiverLayerShellSeatV1FocusNonExclusive
    2 -> handler RiverLayerShellSeatV1FocusNone
    _ -> handler (RiverLayerShellSeatV1Unknown opcode body)

