-- | Bindings for @river-window-management-v1.xml@.
--
-- Generated by @codegen/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.WindowManagement
  (
    RiverWindowManagerV1Event(..)
  , riverWindowManagerV1Interface
  , riverWindowManagerV1Version
  , riverWindowManagerV1Listen
  , riverWindowManagerV1Stop
  , riverWindowManagerV1Destroy
  , riverWindowManagerV1ManageFinish
  , riverWindowManagerV1ManageDirty
  , riverWindowManagerV1RenderFinish
  , riverWindowManagerV1GetShellSurface
  , riverWindowManagerV1ExitSession
  , riverWindowManagerV1ErrorSequenceOrder
  , riverWindowManagerV1ErrorRole
  , riverWindowManagerV1ErrorUnresponsive
  , RiverWindowV1Event(..)
  , riverWindowV1Interface
  , riverWindowV1Version
  , riverWindowV1Listen
  , riverWindowV1Destroy
  , riverWindowV1Close
  , riverWindowV1GetNode
  , riverWindowV1ProposeDimensions
  , riverWindowV1Hide
  , riverWindowV1Show
  , riverWindowV1UseCsd
  , riverWindowV1UseSsd
  , riverWindowV1SetBorders
  , riverWindowV1SetTiled
  , riverWindowV1GetDecorationAbove
  , riverWindowV1GetDecorationBelow
  , riverWindowV1InformResizeStart
  , riverWindowV1InformResizeEnd
  , riverWindowV1SetCapabilities
  , riverWindowV1InformMaximized
  , riverWindowV1InformUnmaximized
  , riverWindowV1InformFullscreen
  , riverWindowV1InformNotFullscreen
  , riverWindowV1Fullscreen
  , riverWindowV1ExitFullscreen
  , riverWindowV1SetClipBox
  , riverWindowV1SetContentClipBox
  , riverWindowV1SetDimensionBounds
  , riverWindowV1ErrorNodeExists
  , riverWindowV1ErrorInvalidDimensions
  , riverWindowV1ErrorInvalidBorder
  , riverWindowV1ErrorInvalidClipBox
  , riverWindowV1DecorationHintOnlySupportsCsd
  , riverWindowV1DecorationHintPrefersCsd
  , riverWindowV1DecorationHintPrefersSsd
  , riverWindowV1DecorationHintNoPreference
  , riverWindowV1EdgesNone
  , riverWindowV1EdgesTop
  , riverWindowV1EdgesBottom
  , riverWindowV1EdgesLeft
  , riverWindowV1EdgesRight
  , riverWindowV1CapabilitiesWindowMenu
  , riverWindowV1CapabilitiesMaximize
  , riverWindowV1CapabilitiesFullscreen
  , riverWindowV1CapabilitiesMinimize
  , RiverDecorationV1Event(..)
  , riverDecorationV1Interface
  , riverDecorationV1Version
  , riverDecorationV1Listen
  , riverDecorationV1Destroy
  , riverDecorationV1SetOffset
  , riverDecorationV1SyncNextCommit
  , riverDecorationV1ErrorNoCommit
  , RiverShellSurfaceV1Event(..)
  , riverShellSurfaceV1Interface
  , riverShellSurfaceV1Version
  , riverShellSurfaceV1Listen
  , riverShellSurfaceV1Destroy
  , riverShellSurfaceV1GetNode
  , riverShellSurfaceV1SyncNextCommit
  , riverShellSurfaceV1ErrorNodeExists
  , riverShellSurfaceV1ErrorNoCommit
  , RiverNodeV1Event(..)
  , riverNodeV1Interface
  , riverNodeV1Version
  , riverNodeV1Listen
  , riverNodeV1Destroy
  , riverNodeV1SetPosition
  , riverNodeV1PlaceTop
  , riverNodeV1PlaceBottom
  , riverNodeV1PlaceAbove
  , riverNodeV1PlaceBelow
  , RiverOutputV1Event(..)
  , riverOutputV1Interface
  , riverOutputV1Version
  , riverOutputV1Listen
  , riverOutputV1Destroy
  , riverOutputV1SetPresentationMode
  , riverOutputV1ErrorInvalidPresentationMode
  , riverOutputV1PresentationModeVsync
  , riverOutputV1PresentationModeAsync
  , RiverSeatV1Event(..)
  , riverSeatV1Interface
  , riverSeatV1Version
  , riverSeatV1Listen
  , riverSeatV1Destroy
  , riverSeatV1FocusWindow
  , riverSeatV1FocusShellSurface
  , riverSeatV1ClearFocus
  , riverSeatV1OpStartPointer
  , riverSeatV1OpEnd
  , riverSeatV1GetPointerBinding
  , riverSeatV1SetXcursorTheme
  , riverSeatV1PointerWarp
  , riverSeatV1ModifiersNone
  , riverSeatV1ModifiersShift
  , riverSeatV1ModifiersCtrl
  , riverSeatV1ModifiersMod1
  , riverSeatV1ModifiersMod3
  , riverSeatV1ModifiersMod4
  , riverSeatV1ModifiersMod5
  , RiverPointerBindingV1Event(..)
  , riverPointerBindingV1Interface
  , riverPointerBindingV1Version
  , riverPointerBindingV1Listen
  , riverPointerBindingV1Destroy
  , riverPointerBindingV1Enable
  , riverPointerBindingV1Disable
  ) where

import Data.ByteString (ByteString)
import Data.Int (Int32)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_window_manager_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverWindowManagerV1Interface :: ByteString
riverWindowManagerV1Interface = "river_window_manager_v1"

-- | The highest version these bindings were generated against.
riverWindowManagerV1Version :: Word32
riverWindowManagerV1Version = 5

-- | @river_window_manager_v1.error.sequence_order@
riverWindowManagerV1ErrorSequenceOrder :: Word32
riverWindowManagerV1ErrorSequenceOrder = 0

-- | @river_window_manager_v1.error.role@
riverWindowManagerV1ErrorRole :: Word32
riverWindowManagerV1ErrorRole = 1

-- | @river_window_manager_v1.error.unresponsive@
riverWindowManagerV1ErrorUnresponsive :: Word32
riverWindowManagerV1ErrorUnresponsive = 2

-- | @river_window_manager_v1.stop@
riverWindowManagerV1Stop :: Connection -> ObjectId -> IO ()
riverWindowManagerV1Stop conn self =
  request conn self 0 (mempty)

-- | @river_window_manager_v1.destroy@
riverWindowManagerV1Destroy :: Connection -> ObjectId -> IO ()
riverWindowManagerV1Destroy conn self =
  request conn self 1 (mempty)
    >> freeObject conn self

-- | @river_window_manager_v1.manage_finish@
riverWindowManagerV1ManageFinish :: Connection -> ObjectId -> IO ()
riverWindowManagerV1ManageFinish conn self =
  request conn self 2 (mempty)

-- | @river_window_manager_v1.manage_dirty@
riverWindowManagerV1ManageDirty :: Connection -> ObjectId -> IO ()
riverWindowManagerV1ManageDirty conn self =
  request conn self 3 (mempty)

-- | @river_window_manager_v1.render_finish@
riverWindowManagerV1RenderFinish :: Connection -> ObjectId -> IO ()
riverWindowManagerV1RenderFinish conn self =
  request conn self 4 (mempty)

-- | @river_window_manager_v1.get_shell_surface@
riverWindowManagerV1GetShellSurface :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverWindowManagerV1GetShellSurface conn self surface =
  do
    id_ <- newObject conn
    request conn self 5 (argObject id_ <> argObject surface)
    pure id_

-- | @river_window_manager_v1.exit_session@
-- Since version 4.
riverWindowManagerV1ExitSession :: Connection -> ObjectId -> IO ()
riverWindowManagerV1ExitSession conn self =
  request conn self 6 (mempty)

-- | Events delivered to a @river_window_manager_v1@.
data RiverWindowManagerV1Event
  = RiverWindowManagerV1Unavailable
  | RiverWindowManagerV1Finished
  | RiverWindowManagerV1ManageStart
  | RiverWindowManagerV1RenderStart
  | RiverWindowManagerV1SessionLocked
  | RiverWindowManagerV1SessionUnlocked
  | RiverWindowManagerV1Window !ObjectId
  | RiverWindowManagerV1Output !ObjectId
  | RiverWindowManagerV1Seat !ObjectId
  | RiverWindowManagerV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_window_manager_v1@ object.
riverWindowManagerV1Listen :: Connection -> ObjectId -> (RiverWindowManagerV1Event -> IO ()) -> IO ()
riverWindowManagerV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverWindowManagerV1Unavailable
    1 -> handler RiverWindowManagerV1Finished
    2 -> handler RiverWindowManagerV1ManageStart
    3 -> handler RiverWindowManagerV1RenderStart
    4 -> handler RiverWindowManagerV1SessionLocked
    5 -> handler RiverWindowManagerV1SessionUnlocked
    6 ->
      handler =<< decode (RiverWindowManagerV1Window <$> getObject) body
    7 ->
      handler =<< decode (RiverWindowManagerV1Output <$> getObject) body
    8 ->
      handler =<< decode (RiverWindowManagerV1Seat <$> getObject) body
    _ -> handler (RiverWindowManagerV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_window_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverWindowV1Interface :: ByteString
riverWindowV1Interface = "river_window_v1"

-- | The highest version these bindings were generated against.
riverWindowV1Version :: Word32
riverWindowV1Version = 5

-- | @river_window_v1.error.node_exists@
riverWindowV1ErrorNodeExists :: Word32
riverWindowV1ErrorNodeExists = 0

-- | @river_window_v1.error.invalid_dimensions@
riverWindowV1ErrorInvalidDimensions :: Word32
riverWindowV1ErrorInvalidDimensions = 1

-- | @river_window_v1.error.invalid_border@
riverWindowV1ErrorInvalidBorder :: Word32
riverWindowV1ErrorInvalidBorder = 2

-- | @river_window_v1.error.invalid_clip_box@
riverWindowV1ErrorInvalidClipBox :: Word32
riverWindowV1ErrorInvalidClipBox = 3

-- | @river_window_v1.decoration_hint.only_supports_csd@
riverWindowV1DecorationHintOnlySupportsCsd :: Word32
riverWindowV1DecorationHintOnlySupportsCsd = 0

-- | @river_window_v1.decoration_hint.prefers_csd@
riverWindowV1DecorationHintPrefersCsd :: Word32
riverWindowV1DecorationHintPrefersCsd = 1

-- | @river_window_v1.decoration_hint.prefers_ssd@
riverWindowV1DecorationHintPrefersSsd :: Word32
riverWindowV1DecorationHintPrefersSsd = 2

-- | @river_window_v1.decoration_hint.no_preference@
riverWindowV1DecorationHintNoPreference :: Word32
riverWindowV1DecorationHintNoPreference = 3

-- | @river_window_v1.edges.none@
riverWindowV1EdgesNone :: Word32
riverWindowV1EdgesNone = 0

-- | @river_window_v1.edges.top@
riverWindowV1EdgesTop :: Word32
riverWindowV1EdgesTop = 1

-- | @river_window_v1.edges.bottom@
riverWindowV1EdgesBottom :: Word32
riverWindowV1EdgesBottom = 2

-- | @river_window_v1.edges.left@
riverWindowV1EdgesLeft :: Word32
riverWindowV1EdgesLeft = 4

-- | @river_window_v1.edges.right@
riverWindowV1EdgesRight :: Word32
riverWindowV1EdgesRight = 8

-- | @river_window_v1.capabilities.window_menu@
riverWindowV1CapabilitiesWindowMenu :: Word32
riverWindowV1CapabilitiesWindowMenu = 1

-- | @river_window_v1.capabilities.maximize@
riverWindowV1CapabilitiesMaximize :: Word32
riverWindowV1CapabilitiesMaximize = 2

-- | @river_window_v1.capabilities.fullscreen@
riverWindowV1CapabilitiesFullscreen :: Word32
riverWindowV1CapabilitiesFullscreen = 4

-- | @river_window_v1.capabilities.minimize@
riverWindowV1CapabilitiesMinimize :: Word32
riverWindowV1CapabilitiesMinimize = 8

-- | @river_window_v1.destroy@
riverWindowV1Destroy :: Connection -> ObjectId -> IO ()
riverWindowV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_window_v1.close@
riverWindowV1Close :: Connection -> ObjectId -> IO ()
riverWindowV1Close conn self =
  request conn self 1 (mempty)

-- | @river_window_v1.get_node@
riverWindowV1GetNode :: Connection -> ObjectId -> IO ObjectId
riverWindowV1GetNode conn self =
  do
    id_ <- newObject conn
    request conn self 2 (argObject id_)
    pure id_

-- | @river_window_v1.propose_dimensions@
riverWindowV1ProposeDimensions :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverWindowV1ProposeDimensions conn self width height =
  request conn self 3 (argInt width <> argInt height)

-- | @river_window_v1.hide@
riverWindowV1Hide :: Connection -> ObjectId -> IO ()
riverWindowV1Hide conn self =
  request conn self 4 (mempty)

-- | @river_window_v1.show@
riverWindowV1Show :: Connection -> ObjectId -> IO ()
riverWindowV1Show conn self =
  request conn self 5 (mempty)

-- | @river_window_v1.use_csd@
riverWindowV1UseCsd :: Connection -> ObjectId -> IO ()
riverWindowV1UseCsd conn self =
  request conn self 6 (mempty)

-- | @river_window_v1.use_ssd@
riverWindowV1UseSsd :: Connection -> ObjectId -> IO ()
riverWindowV1UseSsd conn self =
  request conn self 7 (mempty)

-- | @river_window_v1.set_borders@
riverWindowV1SetBorders :: Connection -> ObjectId -> Word32 -> Int32 -> Word32 -> Word32 -> Word32 -> Word32 -> IO ()
riverWindowV1SetBorders conn self edges width r g b a =
  request conn self 8 (argUInt edges <> argInt width <> argUInt r <> argUInt g <> argUInt b <> argUInt a)

-- | @river_window_v1.set_tiled@
riverWindowV1SetTiled :: Connection -> ObjectId -> Word32 -> IO ()
riverWindowV1SetTiled conn self edges =
  request conn self 9 (argUInt edges)

-- | @river_window_v1.get_decoration_above@
riverWindowV1GetDecorationAbove :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverWindowV1GetDecorationAbove conn self surface =
  do
    id_ <- newObject conn
    request conn self 10 (argObject id_ <> argObject surface)
    pure id_

-- | @river_window_v1.get_decoration_below@
riverWindowV1GetDecorationBelow :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverWindowV1GetDecorationBelow conn self surface =
  do
    id_ <- newObject conn
    request conn self 11 (argObject id_ <> argObject surface)
    pure id_

-- | @river_window_v1.inform_resize_start@
riverWindowV1InformResizeStart :: Connection -> ObjectId -> IO ()
riverWindowV1InformResizeStart conn self =
  request conn self 12 (mempty)

-- | @river_window_v1.inform_resize_end@
riverWindowV1InformResizeEnd :: Connection -> ObjectId -> IO ()
riverWindowV1InformResizeEnd conn self =
  request conn self 13 (mempty)

-- | @river_window_v1.set_capabilities@
riverWindowV1SetCapabilities :: Connection -> ObjectId -> Word32 -> IO ()
riverWindowV1SetCapabilities conn self caps =
  request conn self 14 (argUInt caps)

-- | @river_window_v1.inform_maximized@
riverWindowV1InformMaximized :: Connection -> ObjectId -> IO ()
riverWindowV1InformMaximized conn self =
  request conn self 15 (mempty)

-- | @river_window_v1.inform_unmaximized@
riverWindowV1InformUnmaximized :: Connection -> ObjectId -> IO ()
riverWindowV1InformUnmaximized conn self =
  request conn self 16 (mempty)

-- | @river_window_v1.inform_fullscreen@
riverWindowV1InformFullscreen :: Connection -> ObjectId -> IO ()
riverWindowV1InformFullscreen conn self =
  request conn self 17 (mempty)

-- | @river_window_v1.inform_not_fullscreen@
riverWindowV1InformNotFullscreen :: Connection -> ObjectId -> IO ()
riverWindowV1InformNotFullscreen conn self =
  request conn self 18 (mempty)

-- | @river_window_v1.fullscreen@
riverWindowV1Fullscreen :: Connection -> ObjectId -> ObjectId -> IO ()
riverWindowV1Fullscreen conn self output =
  request conn self 19 (argObject output)

-- | @river_window_v1.exit_fullscreen@
riverWindowV1ExitFullscreen :: Connection -> ObjectId -> IO ()
riverWindowV1ExitFullscreen conn self =
  request conn self 20 (mempty)

-- | @river_window_v1.set_clip_box@
-- Since version 2.
riverWindowV1SetClipBox :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
riverWindowV1SetClipBox conn self x y width height =
  request conn self 21 (argInt x <> argInt y <> argInt width <> argInt height)

-- | @river_window_v1.set_content_clip_box@
-- Since version 3.
riverWindowV1SetContentClipBox :: Connection -> ObjectId -> Int32 -> Int32 -> Int32 -> Int32 -> IO ()
riverWindowV1SetContentClipBox conn self x y width height =
  request conn self 22 (argInt x <> argInt y <> argInt width <> argInt height)

-- | @river_window_v1.set_dimension_bounds@
-- Since version 4.
riverWindowV1SetDimensionBounds :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverWindowV1SetDimensionBounds conn self maxWidth maxHeight =
  request conn self 23 (argInt maxWidth <> argInt maxHeight)

-- | Events delivered to a @river_window_v1@.
data RiverWindowV1Event
  = RiverWindowV1Closed
  | RiverWindowV1DimensionsHint !Int32 !Int32 !Int32 !Int32
  | RiverWindowV1Dimensions !Int32 !Int32
  | RiverWindowV1AppId !(Maybe ByteString)
  | RiverWindowV1Title !(Maybe ByteString)
  | RiverWindowV1Parent !ObjectId
  | RiverWindowV1DecorationHint !Word32
  | RiverWindowV1PointerMoveRequested !ObjectId
  | RiverWindowV1PointerResizeRequested !ObjectId !Word32
  | RiverWindowV1ShowWindowMenuRequested !Int32 !Int32
  | RiverWindowV1MaximizeRequested
  | RiverWindowV1UnmaximizeRequested
  | RiverWindowV1FullscreenRequested !ObjectId
  | RiverWindowV1ExitFullscreenRequested
  | RiverWindowV1MinimizeRequested
  | RiverWindowV1UnreliablePid !Int32
  | RiverWindowV1PresentationHint !Word32
  | RiverWindowV1Identifier !ByteString
  | RiverWindowV1CaptureSessions !Word32
  | RiverWindowV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_window_v1@ object.
riverWindowV1Listen :: Connection -> ObjectId -> (RiverWindowV1Event -> IO ()) -> IO ()
riverWindowV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverWindowV1Closed
    1 ->
      handler =<< decode (RiverWindowV1DimensionsHint <$> getInt <*> getInt <*> getInt <*> getInt) body
    2 ->
      handler =<< decode (RiverWindowV1Dimensions <$> getInt <*> getInt) body
    3 ->
      handler =<< decode (RiverWindowV1AppId <$> getStringMaybe) body
    4 ->
      handler =<< decode (RiverWindowV1Title <$> getStringMaybe) body
    5 ->
      handler =<< decode (RiverWindowV1Parent <$> getObject) body
    6 ->
      handler =<< decode (RiverWindowV1DecorationHint <$> getWord32) body
    7 ->
      handler =<< decode (RiverWindowV1PointerMoveRequested <$> getObject) body
    8 ->
      handler =<< decode (RiverWindowV1PointerResizeRequested <$> getObject <*> getWord32) body
    9 ->
      handler =<< decode (RiverWindowV1ShowWindowMenuRequested <$> getInt <*> getInt) body
    10 -> handler RiverWindowV1MaximizeRequested
    11 -> handler RiverWindowV1UnmaximizeRequested
    12 ->
      handler =<< decode (RiverWindowV1FullscreenRequested <$> getObject) body
    13 -> handler RiverWindowV1ExitFullscreenRequested
    14 -> handler RiverWindowV1MinimizeRequested
    15 ->
      handler =<< decode (RiverWindowV1UnreliablePid <$> getInt) body
    16 ->
      handler =<< decode (RiverWindowV1PresentationHint <$> getWord32) body
    17 ->
      handler =<< decode (RiverWindowV1Identifier <$> getString) body
    18 ->
      handler =<< decode (RiverWindowV1CaptureSessions <$> getWord32) body
    _ -> handler (RiverWindowV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_decoration_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverDecorationV1Interface :: ByteString
riverDecorationV1Interface = "river_decoration_v1"

-- | The highest version these bindings were generated against.
riverDecorationV1Version :: Word32
riverDecorationV1Version = 5

-- | @river_decoration_v1.error.no_commit@
riverDecorationV1ErrorNoCommit :: Word32
riverDecorationV1ErrorNoCommit = 0

-- | @river_decoration_v1.destroy@
riverDecorationV1Destroy :: Connection -> ObjectId -> IO ()
riverDecorationV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_decoration_v1.set_offset@
riverDecorationV1SetOffset :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverDecorationV1SetOffset conn self x y =
  request conn self 1 (argInt x <> argInt y)

-- | @river_decoration_v1.sync_next_commit@
riverDecorationV1SyncNextCommit :: Connection -> ObjectId -> IO ()
riverDecorationV1SyncNextCommit conn self =
  request conn self 2 (mempty)

-- | Events delivered to a @river_decoration_v1@.
data RiverDecorationV1Event
  = RiverDecorationV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_decoration_v1@ object.
riverDecorationV1Listen :: Connection -> ObjectId -> (RiverDecorationV1Event -> IO ()) -> IO ()
riverDecorationV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverDecorationV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_shell_surface_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverShellSurfaceV1Interface :: ByteString
riverShellSurfaceV1Interface = "river_shell_surface_v1"

-- | The highest version these bindings were generated against.
riverShellSurfaceV1Version :: Word32
riverShellSurfaceV1Version = 5

-- | @river_shell_surface_v1.error.node_exists@
riverShellSurfaceV1ErrorNodeExists :: Word32
riverShellSurfaceV1ErrorNodeExists = 0

-- | @river_shell_surface_v1.error.no_commit@
riverShellSurfaceV1ErrorNoCommit :: Word32
riverShellSurfaceV1ErrorNoCommit = 1

-- | @river_shell_surface_v1.destroy@
riverShellSurfaceV1Destroy :: Connection -> ObjectId -> IO ()
riverShellSurfaceV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_shell_surface_v1.get_node@
riverShellSurfaceV1GetNode :: Connection -> ObjectId -> IO ObjectId
riverShellSurfaceV1GetNode conn self =
  do
    id_ <- newObject conn
    request conn self 1 (argObject id_)
    pure id_

-- | @river_shell_surface_v1.sync_next_commit@
riverShellSurfaceV1SyncNextCommit :: Connection -> ObjectId -> IO ()
riverShellSurfaceV1SyncNextCommit conn self =
  request conn self 2 (mempty)

-- | Events delivered to a @river_shell_surface_v1@.
data RiverShellSurfaceV1Event
  = RiverShellSurfaceV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_shell_surface_v1@ object.
riverShellSurfaceV1Listen :: Connection -> ObjectId -> (RiverShellSurfaceV1Event -> IO ()) -> IO ()
riverShellSurfaceV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverShellSurfaceV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_node_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverNodeV1Interface :: ByteString
riverNodeV1Interface = "river_node_v1"

-- | The highest version these bindings were generated against.
riverNodeV1Version :: Word32
riverNodeV1Version = 5

-- | @river_node_v1.destroy@
riverNodeV1Destroy :: Connection -> ObjectId -> IO ()
riverNodeV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_node_v1.set_position@
riverNodeV1SetPosition :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverNodeV1SetPosition conn self x y =
  request conn self 1 (argInt x <> argInt y)

-- | @river_node_v1.place_top@
riverNodeV1PlaceTop :: Connection -> ObjectId -> IO ()
riverNodeV1PlaceTop conn self =
  request conn self 2 (mempty)

-- | @river_node_v1.place_bottom@
riverNodeV1PlaceBottom :: Connection -> ObjectId -> IO ()
riverNodeV1PlaceBottom conn self =
  request conn self 3 (mempty)

-- | @river_node_v1.place_above@
riverNodeV1PlaceAbove :: Connection -> ObjectId -> ObjectId -> IO ()
riverNodeV1PlaceAbove conn self other =
  request conn self 4 (argObject other)

-- | @river_node_v1.place_below@
riverNodeV1PlaceBelow :: Connection -> ObjectId -> ObjectId -> IO ()
riverNodeV1PlaceBelow conn self other =
  request conn self 5 (argObject other)

-- | Events delivered to a @river_node_v1@.
data RiverNodeV1Event
  = RiverNodeV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_node_v1@ object.
riverNodeV1Listen :: Connection -> ObjectId -> (RiverNodeV1Event -> IO ()) -> IO ()
riverNodeV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverNodeV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_output_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverOutputV1Interface :: ByteString
riverOutputV1Interface = "river_output_v1"

-- | The highest version these bindings were generated against.
riverOutputV1Version :: Word32
riverOutputV1Version = 5

-- | @river_output_v1.error.invalid_presentation_mode@
riverOutputV1ErrorInvalidPresentationMode :: Word32
riverOutputV1ErrorInvalidPresentationMode = 0

-- | @river_output_v1.presentation_mode.vsync@
riverOutputV1PresentationModeVsync :: Word32
riverOutputV1PresentationModeVsync = 0

-- | @river_output_v1.presentation_mode.async@
riverOutputV1PresentationModeAsync :: Word32
riverOutputV1PresentationModeAsync = 1

-- | @river_output_v1.destroy@
riverOutputV1Destroy :: Connection -> ObjectId -> IO ()
riverOutputV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_output_v1.set_presentation_mode@
-- Since version 4.
riverOutputV1SetPresentationMode :: Connection -> ObjectId -> Word32 -> IO ()
riverOutputV1SetPresentationMode conn self mode =
  request conn self 1 (argUInt mode)

-- | Events delivered to a @river_output_v1@.
data RiverOutputV1Event
  = RiverOutputV1Removed
  | RiverOutputV1WlOutput !Word32
  | RiverOutputV1Position !Int32 !Int32
  | RiverOutputV1Dimensions !Int32 !Int32
  | RiverOutputV1CaptureSessions !Word32
  | RiverOutputV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_output_v1@ object.
riverOutputV1Listen :: Connection -> ObjectId -> (RiverOutputV1Event -> IO ()) -> IO ()
riverOutputV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverOutputV1Removed
    1 ->
      handler =<< decode (RiverOutputV1WlOutput <$> getWord32) body
    2 ->
      handler =<< decode (RiverOutputV1Position <$> getInt <*> getInt) body
    3 ->
      handler =<< decode (RiverOutputV1Dimensions <$> getInt <*> getInt) body
    4 ->
      handler =<< decode (RiverOutputV1CaptureSessions <$> getWord32) body
    _ -> handler (RiverOutputV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_seat_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverSeatV1Interface :: ByteString
riverSeatV1Interface = "river_seat_v1"

-- | The highest version these bindings were generated against.
riverSeatV1Version :: Word32
riverSeatV1Version = 5

-- | @river_seat_v1.modifiers.none@
riverSeatV1ModifiersNone :: Word32
riverSeatV1ModifiersNone = 0

-- | @river_seat_v1.modifiers.shift@
riverSeatV1ModifiersShift :: Word32
riverSeatV1ModifiersShift = 1

-- | @river_seat_v1.modifiers.ctrl@
riverSeatV1ModifiersCtrl :: Word32
riverSeatV1ModifiersCtrl = 4

-- | @river_seat_v1.modifiers.mod1@
riverSeatV1ModifiersMod1 :: Word32
riverSeatV1ModifiersMod1 = 8

-- | @river_seat_v1.modifiers.mod3@
riverSeatV1ModifiersMod3 :: Word32
riverSeatV1ModifiersMod3 = 32

-- | @river_seat_v1.modifiers.mod4@
riverSeatV1ModifiersMod4 :: Word32
riverSeatV1ModifiersMod4 = 64

-- | @river_seat_v1.modifiers.mod5@
riverSeatV1ModifiersMod5 :: Word32
riverSeatV1ModifiersMod5 = 128

-- | @river_seat_v1.destroy@
riverSeatV1Destroy :: Connection -> ObjectId -> IO ()
riverSeatV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_seat_v1.focus_window@
riverSeatV1FocusWindow :: Connection -> ObjectId -> ObjectId -> IO ()
riverSeatV1FocusWindow conn self window =
  request conn self 1 (argObject window)

-- | @river_seat_v1.focus_shell_surface@
riverSeatV1FocusShellSurface :: Connection -> ObjectId -> ObjectId -> IO ()
riverSeatV1FocusShellSurface conn self shellSurface =
  request conn self 2 (argObject shellSurface)

-- | @river_seat_v1.clear_focus@
riverSeatV1ClearFocus :: Connection -> ObjectId -> IO ()
riverSeatV1ClearFocus conn self =
  request conn self 3 (mempty)

-- | @river_seat_v1.op_start_pointer@
riverSeatV1OpStartPointer :: Connection -> ObjectId -> IO ()
riverSeatV1OpStartPointer conn self =
  request conn self 4 (mempty)

-- | @river_seat_v1.op_end@
riverSeatV1OpEnd :: Connection -> ObjectId -> IO ()
riverSeatV1OpEnd conn self =
  request conn self 5 (mempty)

-- | @river_seat_v1.get_pointer_binding@
riverSeatV1GetPointerBinding :: Connection -> ObjectId -> Word32 -> Word32 -> IO ObjectId
riverSeatV1GetPointerBinding conn self button modifiers =
  do
    id_ <- newObject conn
    request conn self 6 (argObject id_ <> argUInt button <> argUInt modifiers)
    pure id_

-- | @river_seat_v1.set_xcursor_theme@
-- Since version 2.
riverSeatV1SetXcursorTheme :: Connection -> ObjectId -> ByteString -> Word32 -> IO ()
riverSeatV1SetXcursorTheme conn self name size =
  request conn self 7 (argString (Just name) <> argUInt size)

-- | @river_seat_v1.pointer_warp@
-- Since version 3.
riverSeatV1PointerWarp :: Connection -> ObjectId -> Int32 -> Int32 -> IO ()
riverSeatV1PointerWarp conn self x y =
  request conn self 8 (argInt x <> argInt y)

-- | Events delivered to a @river_seat_v1@.
data RiverSeatV1Event
  = RiverSeatV1Removed
  | RiverSeatV1WlSeat !Word32
  | RiverSeatV1PointerEnter !ObjectId
  | RiverSeatV1PointerLeave
  | RiverSeatV1WindowInteraction !ObjectId
  | RiverSeatV1ShellSurfaceInteraction !ObjectId
  | RiverSeatV1OpDelta !Int32 !Int32
  | RiverSeatV1OpRelease
  | RiverSeatV1PointerPosition !Int32 !Int32
  | RiverSeatV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_seat_v1@ object.
riverSeatV1Listen :: Connection -> ObjectId -> (RiverSeatV1Event -> IO ()) -> IO ()
riverSeatV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverSeatV1Removed
    1 ->
      handler =<< decode (RiverSeatV1WlSeat <$> getWord32) body
    2 ->
      handler =<< decode (RiverSeatV1PointerEnter <$> getObject) body
    3 -> handler RiverSeatV1PointerLeave
    4 ->
      handler =<< decode (RiverSeatV1WindowInteraction <$> getObject) body
    5 ->
      handler =<< decode (RiverSeatV1ShellSurfaceInteraction <$> getObject) body
    6 ->
      handler =<< decode (RiverSeatV1OpDelta <$> getInt <*> getInt) body
    7 -> handler RiverSeatV1OpRelease
    8 ->
      handler =<< decode (RiverSeatV1PointerPosition <$> getInt <*> getInt) body
    _ -> handler (RiverSeatV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_pointer_binding_v1 (version 5)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverPointerBindingV1Interface :: ByteString
riverPointerBindingV1Interface = "river_pointer_binding_v1"

-- | The highest version these bindings were generated against.
riverPointerBindingV1Version :: Word32
riverPointerBindingV1Version = 5

-- | @river_pointer_binding_v1.destroy@
riverPointerBindingV1Destroy :: Connection -> ObjectId -> IO ()
riverPointerBindingV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_pointer_binding_v1.enable@
riverPointerBindingV1Enable :: Connection -> ObjectId -> IO ()
riverPointerBindingV1Enable conn self =
  request conn self 1 (mempty)

-- | @river_pointer_binding_v1.disable@
riverPointerBindingV1Disable :: Connection -> ObjectId -> IO ()
riverPointerBindingV1Disable conn self =
  request conn self 2 (mempty)

-- | Events delivered to a @river_pointer_binding_v1@.
data RiverPointerBindingV1Event
  = RiverPointerBindingV1Pressed
  | RiverPointerBindingV1Released
  | RiverPointerBindingV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_pointer_binding_v1@ object.
riverPointerBindingV1Listen :: Connection -> ObjectId -> (RiverPointerBindingV1Event -> IO ()) -> IO ()
riverPointerBindingV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverPointerBindingV1Pressed
    1 -> handler RiverPointerBindingV1Released
    _ -> handler (RiverPointerBindingV1Unknown opcode body)

