-- | Bindings for @river-xkb-bindings-v1.xml@.
--
-- Generated by @codegen/generate-protocol.hs@. Do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module XMonad.River.Protocol.XkbBindings
  (
    RiverXkbBindingsV1Event(..)
  , riverXkbBindingsV1Interface
  , riverXkbBindingsV1Version
  , riverXkbBindingsV1Listen
  , riverXkbBindingsV1Destroy
  , riverXkbBindingsV1GetXkbBinding
  , riverXkbBindingsV1GetSeat
  , riverXkbBindingsV1ErrorObjectAlreadyCreated
  , RiverXkbBindingV1Event(..)
  , riverXkbBindingV1Interface
  , riverXkbBindingV1Version
  , riverXkbBindingV1Listen
  , riverXkbBindingV1Destroy
  , riverXkbBindingV1SetLayoutOverride
  , riverXkbBindingV1Enable
  , riverXkbBindingV1Disable
  , RiverXkbBindingsSeatV1Event(..)
  , riverXkbBindingsSeatV1Interface
  , riverXkbBindingsSeatV1Version
  , riverXkbBindingsSeatV1Listen
  , riverXkbBindingsSeatV1Destroy
  , riverXkbBindingsSeatV1EnsureNextKeyEaten
  , riverXkbBindingsSeatV1CancelEnsureNextKeyEaten
  , riverXkbBindingsSeatV1ModifiersWatch
  ) where

import Data.ByteString (ByteString)
import Data.Word (Word16, Word32)

import XMonad.River.Connection
import XMonad.River.Wire

--------------------------------------------------------------------------------
-- river_xkb_bindings_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbBindingsV1Interface :: ByteString
riverXkbBindingsV1Interface = "river_xkb_bindings_v1"

-- | The highest version these bindings were generated against.
riverXkbBindingsV1Version :: Word32
riverXkbBindingsV1Version = 3

-- | @river_xkb_bindings_v1.error.object_already_created@
riverXkbBindingsV1ErrorObjectAlreadyCreated :: Word32
riverXkbBindingsV1ErrorObjectAlreadyCreated = 0

-- | @river_xkb_bindings_v1.destroy@
riverXkbBindingsV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbBindingsV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_xkb_bindings_v1.get_xkb_binding@
riverXkbBindingsV1GetXkbBinding :: Connection -> ObjectId -> ObjectId -> Word32 -> Word32 -> IO ObjectId
riverXkbBindingsV1GetXkbBinding conn self seat keysym modifiers =
  do
    id_ <- newObject conn
    request conn self 1 (argObject seat <> argObject id_ <> argUInt keysym <> argUInt modifiers)
    pure id_

-- | @river_xkb_bindings_v1.get_seat@
-- Since version 2.
riverXkbBindingsV1GetSeat :: Connection -> ObjectId -> ObjectId -> IO ObjectId
riverXkbBindingsV1GetSeat conn self seat =
  do
    id_ <- newObject conn
    request conn self 2 (argObject id_ <> argObject seat)
    pure id_

-- | Events delivered to a @river_xkb_bindings_v1@.
data RiverXkbBindingsV1Event
  = RiverXkbBindingsV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_bindings_v1@ object.
riverXkbBindingsV1Listen :: Connection -> ObjectId -> (RiverXkbBindingsV1Event -> IO ()) -> IO ()
riverXkbBindingsV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    _ -> handler (RiverXkbBindingsV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_xkb_binding_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbBindingV1Interface :: ByteString
riverXkbBindingV1Interface = "river_xkb_binding_v1"

-- | The highest version these bindings were generated against.
riverXkbBindingV1Version :: Word32
riverXkbBindingV1Version = 3

-- | @river_xkb_binding_v1.destroy@
riverXkbBindingV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbBindingV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_xkb_binding_v1.set_layout_override@
riverXkbBindingV1SetLayoutOverride :: Connection -> ObjectId -> Word32 -> IO ()
riverXkbBindingV1SetLayoutOverride conn self layout =
  request conn self 1 (argUInt layout)

-- | @river_xkb_binding_v1.enable@
riverXkbBindingV1Enable :: Connection -> ObjectId -> IO ()
riverXkbBindingV1Enable conn self =
  request conn self 2 (mempty)

-- | @river_xkb_binding_v1.disable@
riverXkbBindingV1Disable :: Connection -> ObjectId -> IO ()
riverXkbBindingV1Disable conn self =
  request conn self 3 (mempty)

-- | Events delivered to a @river_xkb_binding_v1@.
data RiverXkbBindingV1Event
  = RiverXkbBindingV1Pressed
  | RiverXkbBindingV1Released
  | RiverXkbBindingV1StopRepeat
  | RiverXkbBindingV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_binding_v1@ object.
riverXkbBindingV1Listen :: Connection -> ObjectId -> (RiverXkbBindingV1Event -> IO ()) -> IO ()
riverXkbBindingV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverXkbBindingV1Pressed
    1 -> handler RiverXkbBindingV1Released
    2 -> handler RiverXkbBindingV1StopRepeat
    _ -> handler (RiverXkbBindingV1Unknown opcode body)

--------------------------------------------------------------------------------
-- river_xkb_bindings_seat_v1 (version 3)
--------------------------------------------------------------------------------

-- | The interface name, as advertised by @wl_registry@.
riverXkbBindingsSeatV1Interface :: ByteString
riverXkbBindingsSeatV1Interface = "river_xkb_bindings_seat_v1"

-- | The highest version these bindings were generated against.
riverXkbBindingsSeatV1Version :: Word32
riverXkbBindingsSeatV1Version = 3

-- | @river_xkb_bindings_seat_v1.destroy@
-- Since version 2.
riverXkbBindingsSeatV1Destroy :: Connection -> ObjectId -> IO ()
riverXkbBindingsSeatV1Destroy conn self =
  request conn self 0 (mempty)
    >> freeObject conn self

-- | @river_xkb_bindings_seat_v1.ensure_next_key_eaten@
-- Since version 2.
riverXkbBindingsSeatV1EnsureNextKeyEaten :: Connection -> ObjectId -> IO ()
riverXkbBindingsSeatV1EnsureNextKeyEaten conn self =
  request conn self 1 (mempty)

-- | @river_xkb_bindings_seat_v1.cancel_ensure_next_key_eaten@
-- Since version 2.
riverXkbBindingsSeatV1CancelEnsureNextKeyEaten :: Connection -> ObjectId -> IO ()
riverXkbBindingsSeatV1CancelEnsureNextKeyEaten conn self =
  request conn self 2 (mempty)

-- | @river_xkb_bindings_seat_v1.modifiers_watch@
-- Since version 3.
riverXkbBindingsSeatV1ModifiersWatch :: Connection -> ObjectId -> Word32 -> IO ()
riverXkbBindingsSeatV1ModifiersWatch conn self modifiers =
  request conn self 3 (argUInt modifiers)

-- | Events delivered to a @river_xkb_bindings_seat_v1@.
data RiverXkbBindingsSeatV1Event
  = RiverXkbBindingsSeatV1AteUnboundKey
  | RiverXkbBindingsSeatV1ModifiersUpdate !Word32 !Word32
  | RiverXkbBindingsSeatV1Unknown !Word16 !ByteString
    -- ^ An event this build does not know about, from a server speaking
    -- a newer version of the protocol. Ignoring these is what keeps a
    -- client forward compatible.
  deriving (Eq, Show)

-- | Attach an event handler to a @river_xkb_bindings_seat_v1@ object.
riverXkbBindingsSeatV1Listen :: Connection -> ObjectId -> (RiverXkbBindingsSeatV1Event -> IO ()) -> IO ()
riverXkbBindingsSeatV1Listen conn self handler =
  setListener conn self $ \opcode body -> case opcode of
    0 -> handler RiverXkbBindingsSeatV1AteUnboundKey
    1 ->
      handler =<< decode (RiverXkbBindingsSeatV1ModifiersUpdate <$> getWord32 <*> getWord32) body
    _ -> handler (RiverXkbBindingsSeatV1Unknown opcode body)

