#!/bin/sh
set -eu

# Shared GitHub-style colors, matching the terminal themes.
case "${1:-}" in
    dark)
        background='#0d1117'
        foreground='#e6edf3'
        surface='#161b22'
        muted='#8b949e'
        border='#30363d'
        accent='#58a6ff'
        selection='#1f6feb'
        urgent='#ff7b72'
        ;;
    light)
        background='#ffffff'
        foreground='#1f2328'
        surface='#f6f8fa'
        muted='#656d76'
        border='#d0d7de'
        accent='#0969da'
        selection='#0969da'
        urgent='#cf222e'
        ;;
    *) echo "usage: $0 dark|light" >&2; exit 2 ;;
esac

configuration=${XDG_CONFIG_HOME:-"$HOME/.config"}
mkdir -p "$configuration/rofi" "$configuration/dunst/dunstrc.d"

# Rename complete files so a concurrent launcher or reload never sees partial syntax.
temporary=$(mktemp "$configuration/rofi/.colors.XXXXXX")
trap 'rm -f "$temporary"' EXIT
trap 'exit 1' HUP INT TERM
cat > "$temporary" <<EOF
/* Generated by env/desktop/scripts/theme-apply.sh. */
* {
    background: $background;
    foreground: $foreground;
    lightbg: $surface;
    lightfg: $muted;
    blue: $accent;
    red: $urgent;
    border-color: $border;
    separatorcolor: $border;
    selected-normal-background: $selection;
    selected-normal-foreground: #ffffff;
    selected-active-background: $selection;
    selected-active-foreground: #ffffff;
    selected-urgent-background: $urgent;
    selected-urgent-foreground: $background;
}
window { border: 1px; }
EOF
mv -f "$temporary" "$configuration/rofi/colors.rasi"

temporary=$(mktemp "$configuration/dunst/dunstrc.d/.colors.XXXXXX")
cat > "$temporary" <<EOF
# Generated by env/desktop/scripts/theme-apply.sh.
[theme-low]
    msg_urgency = low
    background = "$background"
    foreground = "$foreground"
    frame_color = "$border"
    highlight = "$accent"

[theme-normal]
    msg_urgency = normal
    background = "$background"
    foreground = "$foreground"
    frame_color = "$border"
    highlight = "$accent"

[theme-critical]
    msg_urgency = critical
    background = "$background"
    foreground = "$foreground"
    frame_color = "$urgent"
    highlight = "$urgent"
EOF
mv -f "$temporary" "$configuration/dunst/dunstrc.d/90-colors.conf"

if systemctl --user --quiet is-active dunst.service; then
    dunstctl reload
fi
