name: xmonad-config
version: "1.0"
synopsis: Michael Sloan's xmonad configuration
author: Michael Sloan
license: MIT
github: mgsloan/mgsloan-dotfiles.git
dependencies:
- aeson
- aeson-pretty
- async
- base
- base64-bytestring
- bytestring
- containers
- directory
- exceptions
- filepath
- http-client
- http-client-tls
- http-conduit
- lens
- lens-aeson
- monad-loops
- path
- path-io
- process
- random
- rex
- rio
- safe
- safe-exceptions
- shell-escape
- stm
- text
- time
- transformers
- typed-process
- unix
- unliftio
- vector
- xmonad
- xmonad-contrib
executables:
  custom-xmonad:
    main: xmonad.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -Wall
    - -fwarn-tabs
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates
    default-extensions:
    - DeriveDataTypeable
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TypeApplications
    - ViewPatterns
    - QuasiQuotes
